name: release

on:
  push:
    tags:
      - "v*.*.*"    

jobs:
  release:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-latest,ubuntu-latest,macos-latest]
        lazarus-versions: [stable] #[dist, stable, 2.0.12, 2.0.10, 2.0.8, 2.0.6]

    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.0.16
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        # include-packages: "Synapse 40.1"

    - name: Build the application
      if: ${{ matrix.operating-system != 'macos-latest' }}
      run: |
        lazbuild -B "pg_timetable_gui.lpi"
        ls

    - name: Build the application (macOS)
      if: ${{ matrix.operating-system == 'macos-latest' }}
      run: lazbuild -B --ws=cocoa "pg_timetable_gui.lpi"

    - name: Pack
      shell: bash
      run: |
          release_name="pg_timetable_gui-${{ matrix.target }}"
          ls -a
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "pg_timetable_gui.exe"
          else
            tar czvf "${release_name}.tar.gz" "pg_timetable_gui"
          fi
    
    - name: Publish Release Artifacts
      uses: softprops/action-gh-release@v1
      with:
          files: |
            *.zip
            *.tar.gz
            LICENSE
